### ISSUE TITLE
Unable to navigate to next page when using a UserDataField

### ISSUE THREAD

**Issue by ngriffin7a** [martin-dominguez/liferay-modules#1]
Steps to reproduce:

1. Create a form named "Test"
2. Add a UserDataField for "First Name" to the first page of the form
3. Add a second page to the form and put a text field on it
4. Save and publish the form
5. Preview the form
6. Click Next

Expected Results:
- Able to navigate to the second page of the form

Actual Results:
- Unable to navigate to the second page of the form due to the following error in the browser:

```
2021-03-06 16:50:16.482 WARN  [http-nio-8080-exec-1][code_jsp:160] {code="400", msg="", uri=/o/dynamic-data-mapping-form-context-provider/}
```

cc @ethib137

**Comment by martin-dominguez** [comment]
Thanks Neil for reporting,

I found the same issue last week, but I didn't have time to check where the
issue is. I'll talk with forms guys and let you know when I solve it.

Again, thanks for using and reporting.

**Comment by martin-dominguez** [comment]
@ngriffin7a Checked and solved. Thank you.
